export const MINOR_PARTICIPANT = "MINOR_PARTICIPANT";
export const ADULT_PARTICIPANT = "ADULT_PARTICIPANT";
export const UNLICENSED_PARTICIPANT = "UNLICENSED_PARTICIPANT";
export const IS_PARTICIPANT_LICENSED = "IS_PARTICIPANT_LICENSED";
